name: test-1

on:

  repository_dispatch:
    types: [test-1]

jobs:

  run-test:

    steps:

      - name: run test 1 (PASS)
        run: |
          set -x
          echo run test 1
          exit 0
