name: source update handler

on: [push, pull_request]

jobs:

  dispatch:

    strategy:
      matrix:
        test: ['test-1', 'test-2', 'test-3']

    runs-on: ubuntu-latest

    steps:
      - name: test dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: ${{ test }}
